###
@baseUrl = http://localhost:4000

###
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "email": "hello@hello.com",
    "password": "hellohello"
} 

# @token

###
GET {{baseUrl}}/api/logout


###
GET {{baseUrl}}/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MzkyMzk0NCwiZXhwIjoxNjkzOTI3NTQ0fQ.TBNnLMJd8kPHuMPAd_wIANKVlME01s2LYoCLrMC8HtQ


###
GET {{baseUrl}}/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5Mzg0MTA5MywiZXhwIjoxNjkzODQ0NjkzfQ.CYd9vPTh-MgEQBuUU_TKlUkQEwKZx2KSM9vgSYnSSbE